#!/usr/bin/with-contenv bash

_term() {
  echo "Caught SIGTERM signal! Stopping cells."
  kill -2 "$pid"
}

if [ -f /config/pydio.json ]; then
    RUN_OPTS="start --grpc_external=33060 --log=production"
else
    RUN_OPTS="install --bind 0.0.0.0:8080 --external $EXTERNALURL --tls_cert_file /config/keys/cert.crt --tls_key_file /config/keys/cert.key"
fi

trap _term SIGTERM

s6-setuidgid abc /app/cells ${RUN_OPTS} & pid=$!

wait
