#!/usr/bin/with-contenv bash

if [ -f /config/pydio.json ]; then
    RUN_OPTS="start --grpc_external=33060 --log=production"
else
    RUN_OPTS="install --bind 0.0.0.0:8080 --external $EXTERNALURL --tls_cert_file /config/keys/cert.crt --tls_key_file /config/keys/cert.key"
fi

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 8080" \
        s6-setuidgid abc /app/cells ${RUN_OPTS}
