#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [ -f "${CELLS_WORKING_DIR}/pydio.json" ]; then
    RUN_OPTS="start --log=production"
else
    RUN_OPTS="configure --site_bind 0.0.0.0:8080 --site_external $EXTERNALURL --tls_cert_file ${CELLS_WORKING_DIR}/keys/cert.crt --tls_key_file ${CELLS_WORKING_DIR}/keys/cert.key"
fi

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 8080" \
        s6-setuidgid abc /app/cells ${RUN_OPTS}
